version: 2

sources:
  - name: bronze
    database: dez2024-413305
    schema: nytaxi

    tables:
      - name: fhv_tripdata
      - name: green_tripdata
      - name: yellow_tripdata

models:
  - name: stg_green_tripdata
    columns:
      - name: trip_id
        tests:
          - unique:
              severity: error
          - not_null:
              severity: error